Pocket/curation-admin-tools

src/curated-corpus/components/AddProspectForm/AddProspectForm.tsx
From the ticket: "When curators click the manual add an item button they want to immediately paste their url into the text field and click submit. Currently they have to first click into the text box to paste the url."
This one-line change fixes the issue.
- https://getpocket.atlassian.net/browse/BACK-1328
=> feat(prospecting): [BACK-1328] Auto focus the item url text box after clicking the manual add item

src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.tsx
Make it easier for the curators to see how many items are already scheduled for the default date (tomorrow) without clicking on another date on the calendar and then clicking back on tomorrow's date again.
Now running the lookup query on initial component load. That does the trick.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1329
https://user-images.githubusercontent.com/22447785/155953943-ff5d46c0-662c-4709-95c0-eec37d3a1540.mov
=> feat(scheduling): [BACK-1329] Show number of scheduled items for default date on modal

src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.test.tsx, src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.tsx, src/curated-corpus/components/MiniScheduleCard/MiniScheduleCard.test.tsx, src/curated-corpus/components/MiniScheduleCard/MiniScheduleCard.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.test.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx, src/curated-corpus/components/RejectedItemListCard/RejectedItemListCard.test.tsx, src/curated-corpus/components/RejectedItemListCard/RejectedItemListCard.tsx
- Updated links to outbound links from the app to have `target="_blank"`.
- Updated unit tests to look out for that in all relevant components.
- https://getpocket.atlassian.net/browse/BACK-1327
=> feat(UI): [BACK-1327] Any time we link to an article, open it in a new tab

.aws/src/pocketAlbApplication.ts
Moving it outside of our VPC so that users can access it without a VPN now that we have authentication implemented
Tickets:
- [BACK-1339]
[BACK-1339]: https://getpocket.atlassian.net/browse/BACK-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(vpc): [BACK-1339] move curation tools out of the vpc

src/collections/components/StoryCard/StoryCard.test.tsx, src/collections/components/StoryCard/StoryCard.tsx
As discussed in Slack - collection stories opening by default in the same tab lead curators away from the single-page app unintentionally.
- Added `target="_blank" to links on the collection story card. Updated tests. ESLint also made me add `rel="noreferrer"` as that apparently mitigates a security risk in older browsers.
Not ticketed in JIRA.
=> fix(collections): add 'target=_blank' to story links

src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.test.tsx, src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.tsx, src/curated-corpus/components/MiniScheduleCard/MiniScheduleCard.styles.tsx, src/curated-corpus/components/MiniScheduleCard/MiniScheduleCard.test.tsx, src/curated-corpus/components/MiniScheduleCard/MiniScheduleCard.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.test.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx, src/curated-corpus/helpers/helperFunctions.test.ts, src/curated-corpus/helpers/helperFunctions.ts
Achieve consistency throughout the curated corpus app with the way topics are displayed.
- Added a helper function that converts topic codes into display names (used
in the topic dropdown), it also provides the `N/A` option for prospects without
a topic set.
- Now using this helper on every content card - approved item card, mini schedule
card and prospect card to show topic names consistently.
- Added and updated unit tests where necessary
Tickets:
- Not ticketed, this has been bugging me for a while (sorry @bassrock 😄)
=> fix(prospecting): Use display names for topics instead of codes with underscores

package-lock.json, package.json, src/curated-corpus/components/AddProspectForm/AddProspectForm.test.tsx, src/curated-corpus/components/AddProspectForm/AddProspectForm.tsx, src/curated-corpus/components/AddProspectFormConnector/AddProspectFormConnector.tsx, src/curated-corpus/components/AddProspectModal/AddProspectModal.tsx, src/curated-corpus/components/index.ts, src/curated-corpus/helpers/helperFunctions.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
Fix a bug - "The mini schedule should perform a refresh (or not use a cache?) after a user schedules a manually added item on the prospecting page."
- Manually added and scheduled items have had its own separate workflow
set up that has a lot in common with the workflow for prospects on the Prospecting
page. Uniting these two workflows into one fixes a UI bug with scheduling -
stories added manually and scheduling straight away do not appear on the sidebar
if they've been scheduled for the next couple of days.
- This initial commit refactors all of the business logic out of the `AddProspectForm`
component into a new `AddProspectFormConnector` component, leaving the form component
to be in charge of the form layout only.
- Updated the code so that adding a manual item workflow delegates …
=> chore(refactor): [BACK-1330] Refactor manual scheduling workflow to fix a bug

src/curated-corpus/components/AddProspectFormConnector/AddProspectFormConnector.tsx, src/curated-corpus/components/AddProspectModal/AddProspectModal.tsx, src/curated-corpus/components/ApprovedItemSearchForm/ApprovedItemSearchForm.test.tsx, src/curated-corpus/components/ApprovedItemSearchForm/ApprovedItemSearchForm.tsx, src/curated-corpus/components/RejectedItemSearchForm/RejectedItemSearchForm.tsx, src/curated-corpus/components/RejectedItemSearchForm/RejectedtemSearchForm.test.tsx, src/curated-corpus/pages/ApprovedItemsPage/ApprovedItemsPage.tsx, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/RejectedItemsPage/RejectedItemsPage.tsx
1. Add a **Reset Filters** button to the Rejected and Approved corpus search forms
2. **Aside**: Set **_Curation Status_** to `Recommendation` in the `ApprovedItemForm` when manually adding a prospect
Tickets:
- [BACK-1333]
https://user-images.githubusercontent.com/16694733/156667776-9bb75610-50df-4249-869e-8b4f4df8d3dd.mov
[BACK-1333]: https://getpocket.atlassian.net/browse/BACK-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(reset filters): [BACK-1333] add a reset filters button to the approved and reject item search form

src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.test.tsx, src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.tsx, src/curated-corpus/helpers/helperFunctions.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
when scheduling an item and having access to only one scheduled surface, auto-select that surface.
- set id to an empty string for manually added prospects
- do not call prospect api after manually adding a prospect
- add some tests
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1336
- https://getpocket.atlassian.net/browse/BACK-1357
=> feat(surface select): auto-select surface if only one is available

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
Reset manually uploaded image when saving two or more prospects consecutively  
Tickets:
- [BACK-1350]
[BACK-1350]: https://getpocket.atlassian.net/browse/BACK-1350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(image upload): [BACK-1350] fix image duplication when saving consective prospects

src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.styles.tsx, src/curated-corpus/components/SplitButton/SplitButton.styles.tsx, src/curated-corpus/components/SplitButton/SplitButton.tsx
Fix minor cosmetic bug, schedule surface selector drop down was being covered by the scheduled item card 
Tickets:
- [BACK-1358]
[BACK-1358]: https://getpocket.atlassian.net/browse/BACK-1358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(schedule item card): [BACK-1358] lower z-index to un block scheduled surface selector dropdown

src/api/fragments/curatedItemData.ts, src/api/generatedTypes.ts, src/curated-corpus/components/AddProspectFormConnector/AddProspectFormConnector.tsx, src/curated-corpus/components/AddProspectModal/AddProspectModal.tsx, src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.tsx, src/curated-corpus/helpers/helperFunctions.test.ts, src/curated-corpus/helpers/helperFunctions.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
Add the `source` field when creating a new approved item. 
Aside: map language field to language enum for reject approved item mutation
Tickets:
- [BACK-1361]
[BACK-1361]: https://getpocket.atlassian.net/browse/BACK-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mutation): [BACK-1361] Add source field to create approved item mutation

src/api/generatedTypes.ts, src/curated-corpus/helpers/definitions.ts, src/curated-corpus/helpers/getProspectFilterOptions.test.ts
update shared data prospect types.
- also make drop down of prospect types dynamic based off generatedTypes
(at the expense of a little readability)
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1376
i chose to sacrifice some readability so our prospect types dropdown will automatically update whenever we add new prospect types.
=> chore(shared data): update prospect types

src/App.tsx, src/collections/pages/CollectionsLandingPage/CollectionsLandingPage.tsx, src/curated-corpus/pages/CuratedCorpusLandingPage/CuratedCorpusLandingPage.tsx
**aside**: add 404 page for invalid curation-tools routes
Tickets:
- [BACK-1322]
- [BACK-1323]
[BACK-1322]: https://getpocket.atlassian.net/browse/BACK-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BACK-1323]: https://getpocket.atlassian.net/browse/BACK-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(pageNotFound): [BACK-1322] Add 404 page for invalid collections app routes

src/curated-corpus/components/SplitButton/SplitButton.styles.tsx, src/curated-corpus/helpers/definitions.ts, src/curated-corpus/helpers/helperFunctions.ts, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Remove the `guidToTimezone` map structure in favour of the newly added `ianaTimezone` field on the scheduled item received from the query
=> chore(refactor): remove unecessary guid to timezone map and fiz z-index on new tab selector

src/curated-corpus/components/AddProspectForm/AddProspectForm.tsx, src/curated-corpus/components/AddProspectFormConnector/AddProspectFormConnector.tsx, src/curated-corpus/components/AddProspectModal/AddProspectModal.tsx
- Add a loading bar when manually adding a prospect
Tickets:
- [BACK-1356]
https://user-images.githubusercontent.com/16694733/161850717-7a3b3a9f-7fa0-4b04-bc78-66b9d614c40d.mov
[BACK-1356]: https://getpocket.atlassian.net/browse/BACK-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  feat(loading state): [BACK-1356] show a loading bar when manually adding a prospect

src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.tsx
URL encode images when showing on the approved list card
=> fix(image-cache): encode the image cache url

src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.test.tsx, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
- Added a "Move to bottom" button to each scheduled item - this button
allows curators to move the item to the bottom of the list of scheduled
items consumed by client applications. This will enable predictable
story order on Pocket Hits surfaces.
- Updated tests.
- The copy on the button. Is there something more succinct? The long copy gets the layout out of whack. Could we get away with just "Reorder"?
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1403
https://user-images.githubusercontent.com/22447785/163322032-aa08dafc-ee04-4919-8eac-257a9f4a4523.mov
=> feat(scheduling): [BACK-1403] Implement "Move to bottom" button on Schedule page

src/api/fragments/prospect.ts, src/api/generatedTypes.ts, src/api/mutations/updateProspectAsCurated.ts, src/curated-corpus/helpers/helperFunctions.test.ts, src/curated-corpus/helpers/helperFunctions.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
-  Update the `updateProspectAsCurated` mutation to use the `id` `(uuid)` and update the mutation input variable.  
- Update the Prospect fragment
Tickets:
- [BACK-1415]
[BACK-1415]: https://getpocket.atlassian.net/browse/BACK-1415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(prospectId): update prospects to use uuid for prospectId property and other updates

src/api/fragments/prospect.ts, src/api/generatedTypes.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
If there is a rejected prospect we should hide it.
This depends on https://github.com/Pocket/prospect-api/pull/431 and https://github.com/Pocket/curated-corpus-api/pull/686
Omit this section if not applicable.
Have you followed the guidelines in our Contributing document?
Omit this section if not applicable.
Anything we should know about deploying this PR?
Documentation here:
- Link to docs
Tickets:
- Link to JIRA tickets
=> fix(rejected): hide rejected prospects

src/curated-corpus/pages/ApprovedItemsPage/ApprovedItemsPage.tsx, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Prevent items without `topic` property from being scheduled/rescheduled 
Tickets:
- [BACK-1437]
[BACK-1437]: https://getpocket.atlassian.net/browse/BACK-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(scheduledItem): Prevent scheduling and rescheduling items without topic

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
Make sure to reset manual submission to false when a user clicks on a prospect card
Long term I think we should update 
```
approvedItem={transformProspectToApprovedItem(
currentProspect,
isRecommendation,
isManualSubmission
)}
```
to not use the isManualSubmission state variable and instead rely on there being a prospect id
=> fix(manual): resetting manual submission when from prospect

src/api/client.ts
❌  DO NOT MERGE ❌ 
After adding the `csrfPrevention:true` property on the Admin-api gateway instance, the image upload requests were being blocked due to the `content-type` header for that request being `multipart/form-data`. This change fixes that and allows for successful image uploads
Tickets:
- [BACK-1422]
[BACK-1422]: https://getpocket.atlassian.net/browse/BACK-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(preflight header): [BACK-1422] Add pre flight header to apollo client instance

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
After adding a manual prospect/item and then trying to schedule it, users were getting an error toast even though the item was being successfully scheduled. This change fixes that.
Tickets:
- [BACK-1456]
[BACK-1456]: https://getpocket.atlassian.net/browse/BACK-1456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(manual schedule): [BACK-1456] Fix manual scheduling throwing an error

src/_shared/components/Header/Header.test.tsx, src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.test.tsx, src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.test.tsx, src/curated-corpus/components/ImageUpload/ImageUpload.test.tsx, src/curated-corpus/components/MiniScheduleCard/MiniScheduleCard.test.tsx, src/curated-corpus/components/RejectedItemListCard/RejectedItemListCard.test.tsx, src/curated-corpus/components/ScheduleItemModal/ScheduleItemModal.test.tsx, src/curated-corpus/components/ScheduleItemModal/ScheduleItemModal.tsx, src/curated-corpus/components/ScheduledSurfaceGroupedList/ScheduledSurfaceGroupedList.test.tsx, src/curated-corpus/helpers/helperFunctions.test.ts, src/curated-corpus/integration-test-mocks/getScheduledItemCounts.ts, src/curated-corpus/integration-test-mocks/getScheduledItems.ts, src/curated-corpus/integration-test-mocks/getScheduledSurfacesForUser.ts, src/curated-corpus/integration-test-mocks/utils.ts
Improve test coverage of our frontend code. Note: no change to functionality, tests added/amended only.
- Added the missing unit tests.
- Added comments to component props.
- Fixed up test mocks elsewhere whenever the IDE highlighted missing props.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1535
=> chore(tests): [BACK-1535] Add unit tests for ScheduleItemModal component

src/_shared/components/_form-elements/FormikTextField/FormikTextField.test.tsx, src/collections/components/AuthorForm/AuthorForm.tsx, src/collections/components/CollectionForm/CollectionForm.tsx, src/collections/components/CollectionPartnerAssociationForm/CollectionPartnerAssociationForm.test.tsx, src/collections/components/CollectionPartnerAssociationForm/CollectionPartnerAssociationForm.tsx, src/collections/components/PartnerForm/PartnerForm.tsx, src/collections/components/StoryForm/StoryForm.tsx
Remove warnings from unit tests that were polluting the test output - they were especially annoying to wade through in watch mode. The warnings related to a deprecated component property - switched a textarea component from `rows` to `minRows`.
=> chore(tests): Remove deprecated warning from Collections tests

src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.styles.tsx, src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.test.tsx, src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.styles.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.test.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx
Make it easier for the curators to see whether a prospect coming through is a syndicated article or not.
- Added a "Syndicated" tag to syndicated prospects on the prospecting page.
- Added unit tests.
- Moved language to secondary info area to free up the best real estate for the "Syndicated" tag.
- Updated the look of the saves and prospect type/source info under the prospect thumbnail image.
Note: screenshots are in Slack.
https://getpocket.atlassian.net/browse/BACK-1542
=> feat(UI): [BACK-1542] Show Syndication in Prospecting

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
Hoist lazy query function/hook declarations to that they are available in the lexical scope for the initial page render query request.
https://user-images.githubusercontent.com/16694733/181013682-9b9e649f-9b89-4911-ad75-3664d3999c0a.mov
https://user-images.githubusercontent.com/16694733/181013734-eedfbf3b-a980-4db6-a085-8cdd6f166d8c.mov
=> fix(prospecting page): Fix prospecting page not rendering anything after switching to it from another page

src/curated-corpus/components/RejectedItemListCard/RejectedItemListCard.test.tsx
As the PR title says.
- Added a test for publisher (a later addition to the rejected item card).
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1530
=> chore(tests): [BACK-1530] Improve unit tests for RejectedListItemCard component

src/curated-corpus/components/ApprovedItemCardWrapper/ApprovedItemCardWrapper.test.tsx, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.test.tsx, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx
To have all links in the app working.
- Fixed the bug.
- Added regression tests to the two wrapper components that link to the Corpus Item page.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1568
=> fix(schedule page): [BACK-1568] "View" links to go to Corpus Item pages off Schedule page are broken

src/curated-corpus/components/ScheduleSummaryConnector/ScheduleSummaryConnector.tsx
Follow-up to BACK-1555 which included a refactor of scheduled summary on the Prospecting page. If no items are scheduled for the default day, the Prospecting page dies with a type error. Discovered on Dev, does not affect Prod at the moment as they have stories scheduled for tomorrow.
=> fix(prospecting): Fix Prospecting page breaking on no scheduled items.

src/api/generatedTypes.ts, src/curated-corpus/components/RejectedItemListCard/RejectedItemListCard.test.tsx, src/curated-corpus/components/RejectedItemListCard/RejectedItemListCard.tsx
Sync up the frontend with recent backend changes. Fix a long-running bug in the Curation Admin Tools when occasionally the Prospecting page crashes on fetching prospects. See https://github.com/Pocket/curated-corpus-api/pull/763. 
- Update generated types (just the ones we need for rejected items to stop crashing the Prospecting page).
- Update tests for the `RejectedItemListCard` component to test for optional props. Update the component itself to display 'N/A' if metadata is missing.
https://getpocket.atlassian.net/browse/BACK-1492
=> feat(rejected items): [BACK-1492] Make fields optional on rejected items

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
While working on https://getpocket.atlassian.net/browse/BACK-1570, I noticed  that the very first query the Prospecting page loads doesn’t show anything  while the API call is in progress unlike the other queries on the page.
I’ve added the HandleApiResponse component to show the loading state for that first query - this is the query that loads the surfaces the user has access to for the dropdown menu.
https://user-images.githubusercontent.com/22447785/188535579-10868a21-99a8-4982-a8fc-9129b67d6511.mov
https://getpocket.atlassian.net/browse/BACK-1592
=> fix(prospecting page): [BACK-1592] Add loading indicator to Prospecting page

src/api/client.ts, src/curated-corpus/components/actions/RejectCorpusItemAction/RejectCorpusItemAction.test.tsx, src/curated-corpus/components/actions/RejectCorpusItemAction/RejectCorpusItemAction.tsx, src/curated-corpus/components/index.ts, src/curated-corpus/integration-test-mocks/rejectApprovedItem.ts, src/curated-corpus/pages/CorpusItemPage/CorpusItemPage.tsx, src/curated-corpus/pages/CorpusPage/CorpusPage.tsx
Let users reject the corpus item right from the Corpus Item page.
Note that the reason I have to go and add a corpus item before rejecting it is because everything else on Dev has scheduled entries and would not be able to be moved to the rejected pile anyway. The walkthrough shows both the new action off the Curated Item page and also the old one on the Corpus page - this is now powered by same code, just making sure it works after the refactor.
https://user-images.githubusercontent.com/22447785/188348746-e8b28fcd-da5a-424d-b8ba-36159d225549.mov
https://getpocket.atlassian.net/browse/BACK-1570
=> feat(corpus item): [BACK-1570] Allow Reject action from corpus item page

src/curated-corpus/components/actions/EditCorpusItemAction/EditCorpusItemAction.test.tsx, src/curated-corpus/components/actions/EditCorpusItemAction/EditCorpusItemAction.tsx, src/curated-corpus/helpers/approvedItem.ts, src/curated-corpus/integration-test-mocks/updateApprovedItem.ts, src/curated-corpus/pages/CorpusItemPage/CorpusItemPage.tsx, src/curated-corpus/pages/CorpusPage/CorpusPage.tsx
To get the last remaining actions working on the Corpus Item page. The "Edit" action was targeted for this ticket, however since the image upload/reupload form and mutation are part of the form component, they came along for the ride and got included in this ticket instead of being addressed separately in BACK-1572. 
- Refactored the Edit action out of the Corpus page and into its own component.
- Reused this component on the Corpus Item page. Both Edit and Upload Image actions are now working on the Corpus Item page.
- Added tests.
Demonstrates that the old, now refactored action on the Corpus page is working, and then moves on to the Corpus Item page to demonstrate the very same functionality working there, too. 
https://user-images.githubusercontent.com/22447785/189311842-2f603c40-5383- …
=> feat(corpus item): [BACK-1559] Allow "Edit" action from the full details page

src/api/fragments/CollectionData.ts, src/api/generatedTypes.ts
Add labels to collection data returned with the fragment that is used in mutations and queries so that we can see this data on the frontend. 
Note: there is no change to current functionality; manually verified on Dev that things don't break after this update.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1642
=> feat(labels): [BACK-1642] Update CollectionData fragment

src/collections/components/CollectionInfo/CollectionInfo.test.tsx, src/collections/components/CollectionInfo/CollectionInfo.tsx, src/collections/components/CollectionListCard/CollectionListCard.test.tsx, src/collections/components/CollectionListCard/CollectionListCard.tsx
- Updating the CollectionInfo and CollectionListCard components to show labels. The label icon (currently used for topics / curation categories) is used for labels.
- Related integration tests are updated.
Tickets:
- [https://getpocket.atlassian.net/browse/BACK-1643](https://getpocket.atlassian.net/browse/BACK-1643)
=> BACK-1643: Update CollectionInfo and CollectionListCard components

src/api/generatedTypes.ts, src/api/mutations/createCollection.ts, src/api/mutations/updateCollection.ts, src/collections/components/CollectionForm/CollectionForm.test.tsx, src/collections/components/CollectionForm/CollectionForm.tsx, src/collections/components/CollectionForm/CollectionForm.validation.tsx, src/collections/pages/AddCollectionPage/AddCollectionPage.tsx, src/collections/pages/CollectionPage/CollectionPage.tsx
Until https://github.com/Pocket/collection-api/pull/1010 is in.
Finally! This PR will enable curators to add/update/remove labels on a collection, both when creating one and updating an existing collection
https://user-images.githubusercontent.com/22447785/201078944-c28eeb42-1fa1-414b-aca3-147652fcb2b6.mov
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1646
=> feat(labels): [BACK-1646] Be able to create/update collections with labels

src/collections/components/CollectionInfo/CollectionInfo.tsx, src/collections/components/CollectionListCard/CollectionListCard.tsx, src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.tsx, src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx, src/curated-corpus/components/RejectedItemListCard/RejectedItemListCard.tsx
With `labels` now using the MUI material label icon, `curation category / topic` icon is now updated to the [MUI category icon](https://mui.com/material-ui/material-icons/?query=category&selected=Category)
Tickets:
- [https://getpocket.atlassian.net/browse/BACK-1687](https://getpocket.atlassian.net/browse/BACK-1687)
Example:
=> BACK-1687: update curation category / topic icon

src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.test.tsx, src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx
We need to be able to dismiss prospects that are already in corpus.
Tickets:
- [BACK-1691]
[BACK-1691]: https://getpocket.atlassian.net/browse/BACK-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dismissProspect): allow dismiss for prospects already in corpus

src/api/generatedTypes.ts, src/api/queries/getSearchCollections.ts, src/api/queries/labels.ts, src/collections/components/CollectionSearchForm/CollectionSearchForm.tsx, src/collections/components/CollectionSearchForm/CollectionSearchForm.validation.tsx, src/collections/pages/CollectionSearchPage/CollectionSearchPage.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx
So that users can search by one or more labels on the "Search" page.
Did a minor refactor to the search query itself (sending all the filters as one variable instead of individual variables) and updated the "Status" field - the markup on the old one was a bit wonky (labels wouldn't shrink) and it also produced a warning on dev. Additionally, it was missing one of the status values - "Review". Added that, too.
https://user-images.githubusercontent.com/22447785/202342577-e940fa6c-4692-4931-99fa-d2d14538381f.mov
https://getpocket.atlassian.net/browse/BACK-1647
=> feat(labels): [BACK-1647] Update `CollectionSearchForm` component

src/collections/components/AuthorForm/AuthorForm.test.tsx, src/collections/components/AuthorForm/AuthorForm.validation.tsx
Update the `AuthorForm` component validation to set minimum author name length to two
=> fix(authorName): set minimum author name length to two

src/collections/components/LabelListCard/LabelListCard.styles.tsx, src/collections/components/LabelListCard/LabelListCard.test.tsx, src/collections/components/LabelListCard/LabelListCard.tsx, src/collections/components/index.ts, src/collections/pages/CollectionsLandingPage/CollectionsLandingPage.tsx, src/collections/pages/LabelListPage/LabelListPage.tsx, src/collections/pages/index.ts, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.test.tsx, src/curated-corpus/helpers/helperFunctions.test.ts
* Adding a labels page to display non-paginated list of available labels. Only label names are displayed. 
* `Add Label` button does not function yet. This functionality will be implemented in another PR.
Tickets:
- [https://getpocket.atlassian.net/browse/BACK-1690](https://getpocket.atlassian.net/browse/BACK-1690)
Video
https://user-images.githubusercontent.com/16909783/204396720-8c70eb1a-1b66-4886-afbc-a32db03e6468.mov
=> BACK-1690: Adding Labels page

src/_shared/components/HandleApiResponse/HandleApiResponse.tsx, src/collections/pages/CollectionSearchPage/CollectionSearchPage.tsx, src/collections/pages/CollectionsHomePage/CollectionsHomePage.tsx
Transition all Collections code to MUI 5 except for Collection & Collection List pages which will be tackled in the next ticket.
- Minimal updates required here, so upgraded one of the shared components alongside the pages: `HandleApiResponse`.
https://getpocket.atlassian.net/browse/BACK-1720
=> feat(mui): [BACK-1720] MUI 5 Upgrade: Transition Collection Search, home and landing pages

package-lock.json, package.json, src/collections/components/CollectionForm/CollectionForm.test.tsx, src/curated-corpus/components/ApprovedItemCurationHistory/ApprovedItemCurationHistory.tsx, src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.tsx, src/curated-corpus/components/ApprovedItemInfo/ApprovedItemInfo.tsx, src/curated-corpus/components/ApprovedItemModal/ApprovedItemModal.tsx, src/curated-corpus/components/RejectItemForm/RejectItemForm.tsx, src/curated-corpus/components/RejectItemModal/RejectItemModal.tsx, src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.test.tsx, src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.tsx, src/curated-corpus/components/ScheduleItemFormConnector/ScheduleItemFormConnector.test.tsx, src/curated-corpus/components/ScheduleItemFormConnector/ScheduleItemFormConnector.tsx, src/curated-corpus/components/ScheduleItemModal/ScheduleItemModal.tsx, src/curated-corpus/components/actions/EditCorpusItemAction/EditCorpusItemAction.tsx, src/curated-corpus/components/actions/RejectCorpusItemAction/RejectCorpusItemAction.tsx, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.test.tsx, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.tsx, src/curated-corpus/components/index.ts, src/curated-corpus/helpers/helperFunctions.test.ts, src/curated-corpus/pages/CorpusItemPage/CorpusItemPage.tsx
This change encompasses updates to the main forms and form action components for "Edit", "Schedule" and "Reject" actions in addition to UI updates to the Corpus Item page itself.
As such, the most work was to tame the date pickers used on the Schedule Item form - using MUI's x-date-pickers package proved to be the easier option of the two (the mui/lab package is being removed with this PR as that was the second option, and we don't use Lab components for anything else).
Tests interacting with the date pickers have been updated; an unfinished integration test has been updated but not yet finished as that will come in a separate test sweep PR.
This PR's target is the `feature/mui-5-upgrade` branch. 
https://getpocket.atlassian.net/browse/BACK-1757
=> feat(mui5): [BACK-1757] Transition Corpus Item page to MUI 5

.aws/package.json
fix incorrect file extension for aws folder lint check
Tickets:
- [chore ticket](https://getpocket.atlassian.net/browse/BACK-1725)
[BACK-1725]: https://getpocket.atlassian.net/browse/BACK-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(husky): fix incorrect file extension for aws folder lint check

src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.tsx, src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx
Apply one last tweak following the upgrade to MUI 5. It is documented in the ticket but I forgot to include it with the other fixes in https://github.com/Pocket/curation-admin-tools/pull/989. 
Before (prospect card & existing prospect card):
After:
https://getpocket.atlassian.net/browse/BACK-1770
=> fix(mui5): [BACK-1770] Restore less round corners on prospect card thumbnail images

.eslintrc.js
Remove annoying GitHub linter warnings for files under the `.aws` folder, such as on this PR under the heading "Unchanged files with check annotations": https://github.com/Pocket/curation-admin-tools/pull/990/files. 
We're not using Pocket's backend-centric `eslint-config` package for this repository, so we need to add the ignore pattern manually.
=> fix(linting): Run the lint check over AWS files

src/App.tsx, src/_shared/hooks/useMozillaAuth/useMozillaAuth.ts, src/_shared/pages/LandingPage/LandingPage.tsx, src/curated-corpus/pages/CuratedCorpusLandingPage/CuratedCorpusLandingPage.tsx, src/moderation/pages/ModerationLandingPage/ModerationLandingPage.tsx, src/moderation/pages/index.ts
- Added routing, menu, and page scaffolding to accommodate the new "Moderation" tool to Curation Admin Tools.
- Note while I added menu links and links to the intro on the landing page for the Moderation tool, I didn't actually add components for these pages so an attempt to follow the links will end up in a 404 for now, until they're added in subsequent tasks.
https://user-images.githubusercontent.com/22447785/222998578-d4603653-100a-4b5f-990b-097e1a6a31de.mov
Tickets:
- https://getpocket.atlassian.net/browse/OSL-166
=> feat(moderation): {OSL-166] Add new "Moderation" tool to the suite

src/api/fragments/ShareableListCompleteProps.ts, src/api/fragments/ShareableListItemProps.ts, src/api/generatedTypes.ts, src/moderation/components/ShareableListCard/ShareableListCard.test.tsx, src/moderation/components/ShareableListCard/ShareableListCard.tsx, src/moderation/components/ShareableListFormConnector/ShareableListFormConnector.test.tsx, src/moderation/components/ShareableListFormConnector/ShareableListFormConnector.tsx, src/moderation/components/ShareableListModal/ShareableListModal.test.tsx, src/moderation/components/ShareableListModal/ShareableListModal.tsx, src/moderation/components/ShareableListModerationForm/ShareableListModerationForm.test.tsx, src/moderation/components/ShareableListRestorationForm/ShareableListRestorationForm.test.tsx, src/moderation/components/ShareableListRestorationForm/ShareableListRestorationForm.tsx, src/moderation/components/ShareableListRestorationForm/ShareableListRestorationForm.validation.tsx, src/moderation/components/index.ts, src/moderation/integration-test-mocks/moderateShareableLists.ts
Adding a modal for restoring a shareable list after it has been hidden. Updated and added tests for this functionality.
- [https://getpocket.atlassian.net/browse/OSL-464](https://getpocket.atlassian.net/browse/OSL-464)
https://user-images.githubusercontent.com/16909783/235533038-443246d6-0e50-4470-a8e4-6848591a9ae7.mov
=> OSL-464: Adding shareable list restoration functionality to moderation tool

src/moderation/components/ShareableListItemCard/ShareableListItemCard.test.tsx, src/moderation/components/ShareableListItemCard/ShareableListItemCard.tsx
Display notes on admin moderation screen for a list item.
- [https://getpocket.atlassian.net/browse/OSL-398](https://getpocket.atlassian.net/browse/OSL-398)
=> OSL-398: displaying list item notes in moderation tool

src/_shared/utils/applyApTitleCase.test.ts, src/_shared/utils/applyApTitleCase.ts, src/_shared/utils/applyCurlyQuotes.test.ts, src/_shared/utils/applyCurlyQuotes.ts, src/collections/components/StoryForm/StoryForm.tsx
Based on meeting we had with Editorial team, we wanted to add a button that fixes the title and the straight apostrophe's in titles when populating from a url.
Created two helper functions for these two fixes:
Add curly quotes and fix AP style title case for titles in collections (see tests also)
Per request from Editorial team, added a 'fix excerpt' button as well
Documentation here:
1. Casing follows AP style here - https://headlinecapitalization.com/
2. Regular single and double quotes replaced by curly ones
Tickets:
[Jira](https://getpocket.atlassian.net/jira/software/projects/TML/boards/123?assignee=637ba9dca593cb822e93c33f)
=> [TML-75] Add title fix button

src/api/fragments/ShareableListItemProps.ts, src/api/generatedTypes.ts, src/moderation/components/ShareableListItemCard/ShareableListItemCard.test.tsx, src/moderation/components/ShareableListItemCard/ShareableListItemCard.tsx
This is part of the foundational refactor rollback. Updating public schema to use `ShareableListItem` type instead of `ShareableListItemAdmin` type.
- [https://getpocket.atlassian.net/browse/OSL-575](https://getpocket.atlassian.net/browse/OSL-575)
=> OSL-575: Update public schema to use ShareableListItem type instead of ShareableListItemAdmin type

src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Allow curators to schedule articles one year in advance, e.g. for Christmas next year
Documentation here:
- Following is the doc that was used to add the initial `59` days. Seems like it was chosen so curators don't see to many schedule days.
- New requirement is now for `365` days.
- [Link to docs](https://docs.google.com/document/d/15vDPv7RvQwhz3K4Vl3UinHFcDx6ZdCDxlNMPwlZIhb4/edit)
Tickets:
- Previous ticket for 59 days - https://getpocket.atlassian.net/browse/BACK-1363
- New ticket - https://getpocket.atlassian.net/browse/TML-97
=> Allow scheduling up to 1 year

src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.tsx
Similar to what we did for collections, we want to add fix title and excerpt buttons on the corpus items
Tickets:
- [Jira](https://getpocket.atlassian.net/browse/TML-99?atlOrigin=eyJpIjoiYmRjMTRhYjMzNTBhNGQ1ZjhiZTM3ZWUzZjJiMjAxYzkiLCJwIjoiaiJ9)
=> Fix title and Fix excerpt buttons on corpus items

src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.test.tsx, src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.tsx, src/curated-corpus/components/ScheduleItemFormConnector/ScheduleItemFormConnector.tsx, src/curated-corpus/components/ScheduleSummaryConnector/ScheduleSummaryConnector.tsx, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx, src/curated-corpus/pages/CorpusItemPage/CorpusItemPage.tsx, src/curated-corpus/pages/CorpusPage/CorpusPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Adds the schedule context to the schedule and corpus tools (similar to the prospect tool)
The editors also asked to add the scheduled context in 3 new spots:
1. Corpus schedule on corpus page
2. Reschedule on the schedule page
3. After scheduling from prospecting page
☑️ Fixed tests
☑️ Added new test for new scheduled context
Tickets:
- [Jira](https://getpocket.atlassian.net/browse/TML-96)
=> Add schedule context to 'Schedule' and 'Corpus'

src/curated-corpus/pages/CorpusPage/CorpusPage.tsx
Per curators' request, remove this from the corpus page. We're showing the schedule context in the modal now.
Slack thread - https://mozilla.slack.com/archives/C05FLVAF4SK/p1689779984911579?thread_ts=1689620560.445929&cid=C05FLVAF4SK
Tickets:
- [Jira](https://getpocket.atlassian.net/browse/TML-137)
=> Remove schedule context from corpus page

src/api/generatedTypes.ts, src/curated-corpus/integration-test-mocks/getScheduledSurfacesForUser.ts
Add the new RSS_LOGISTIC_RECENT prospect type to NEW_TAB_EN_US surface for the new tab recent content experiment.
Will be merged before this https://github.com/Pocket/prospect-api/pull/572.
Related to: https://github.com/Pocket/curated-corpus-api/pull/1007
JIRA ticket:
[MC-319](https://mozilla-hub.atlassian.net/browse/MC-319)
[MC-319]: https://mozilla-hub.atlassian.net/browse/MC-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(prospectType): [MC-319] Add rss_logistic_recent prospect type to new_tab_en_us

src/curated-corpus/helpers/prospects.test.ts, src/curated-corpus/helpers/prospects.ts
Use the right language when manually adding a French, Spanish, or Italian prospect.
1. [Run the admin tool locally](https://mozilla-hub.atlassian.net/browse/MC-96) with `REACT_APP_ADMIN_API_ENDPOINT=https://admin-api.getpocket.dev`
2. Manually add a prospect with url https://www.revistavanityfair.es/articulos/centro-de-arte-hortensia-herrero-juan-roig-mercadona-valencia-obras-valencia
Before, the language would default to German. Now, the language is correctly identified as Spanish:
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-96
=> fix(prospects): [MC-96] Use correct language when adding prospect

src/_shared/utils/applyApTitleCase.test.ts, src/_shared/utils/applyApTitleCase.ts
Corrie raised [the issue](https://mozilla.slack.com/archives/C05FLVAF4SK/p1701709206385509) that `Fix Title` wasn't working properly when there are apostrophes.
This can now be tested on [dev](https://curation-admin-tools.getpocket.dev/) from `Private Mode or Incognito` by going to `/curated-corpus/corpus`, selecting `Edit` on a tile. Try the following text in the title and click `Fix Title`
```
“Integrated thriving” can fix unhelpful buzz words like “girlboss” and “snail girl”
```
The result should be
```
“Integrated Thriving” Can Fix Unhelpful Buzz Words Like “Girlboss” and “Snail Girl”
``` 
Tickets:
-  [Slack issue](https://mozilla.slack.com/archives/C05FLVAF4SK/p1701709206385509)
Added the missing separators so that we capture the missing apostrophes
=> Fix casing after apostrophe

src/_shared/utils/applyApTitleCase.test.ts, src/_shared/utils/applyApTitleCase.ts
Kimi found that contractions stopped working for "Fix Title" and suggested that we only handle double apostrophes for now - https://mozilla.slack.com/archives/C05FLVAF4SK/p1701709206385509
Small code change to remove the single apostrophes.
=> Fix contractions in "Fix Title"

src/api/generatedTypes.ts, src/curated-corpus/integration-test-mocks/getScheduledSurfacesForUser.ts
Add new prospect type CONSTRAINT_SCHEDULE, which is a set of prospects without using the same topics and publishers too many times.
I looked at https://github.com/Pocket/curation-admin-tools/pull/1146/commits/cbf90bfed5242ae906db10821b4fca02eab8f446 to see which changes need to be made.
JIRA ticket:
- [MC-403](https://mozilla-hub.atlassian.net/browse/MC-403)
I created a Confluence doc with steps on how to create a new Prospect Type:
- https://mozilla-hub.atlassian.net/wiki/spaces/PE/pages/516817186/How+to+add+a+new+Prospect+Type
Related PRs:
- https://github.com/Pocket/prospect-api/pull/574
- https://github.com/Pocket/dl-metaflow-jobs/pull/250
- https://github.com/Pocket/curated-corpus-api/pull/1009
[MC-403]: https://mozilla-hub.atlassian.net/browse/MC-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> feat(prospectType): [MC-403] Add CONSTRAINT_SCHEDULE

src/curated-corpus/components/actions/RemoveProspectAction/RemoveProspectAction.tsx
only show prospect removal reasons on SlateSchedulerV2 prospect type
- remove showing the modal on the old SlateScheduler prospect type
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-718
=> refactor: only show prospect removal reasons on SlateSchedulerV2 prospect type

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Allow the curators to add new curated items straight from the Schedule page and be able to proceed to scheduling them straight away.
- Removed the word "Optional" from manual item addition workflow
- With minor changes, added the workflow already in use on the Prospecting page, which added a handful more state variables onto the page, plus two more mutations - one for uploading the item's thumbnail image, and the other for creating the item itself.
https://github.com/Pocket/curation-admin-tools/assets/22447785/a9e26880-841b-41a6-917f-938b01e78525
https://mozilla-hub.atlassian.net/browse/MC-417
=> feat(scheduling): [MC-417] Curators can manually add an item from Schedule view

src/_shared/components/CorpusItemCardImage/CorpusItemCardImage.tsx, src/api/fragments/scheduledItemData.ts, src/api/generatedTypes.ts, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx, src/curated-corpus/components/SuggestedScheduleItemListCard/SuggestedScheduleItemListCard.tsx
Asserting on the `ScheduledItem` object / type's newly added `source` enum value to determine if it is an ML scheduled item and show the `ML` label on the scheduled item card.
Tickets:
- [MC-550](https://mozilla-hub.atlassian.net/browse/MC-550)
Ideally, I didn't want to add another prop and drill it down. Due to the lack of time, I've implemented it this way. Although, a more graceful solution would require some refactoring such that `CorpusCardImage` component is able to take an `item` prop of `ScheduledCorpusItem` as well. 
I leave it to the smart people of this team ❤️  
[MC-550]: https://mozilla-hub.atlassian.net/browse/MC-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mlScheduled): [MC-550] Show ML label on ML scheduled items

src/api/generatedTypes.ts, src/api/mutations/createScheduledCorpusItem.ts, src/api/mutations/rescheduledScheduledItem.ts, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
until backend API change has shipped. these PRs will need to be coordinated.
send a `source` value when rescheduling items.
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-763
=> feat: send source value for rescheduled items

.circleci/config.yml
update remote docker version based on [circleCI docs](https://circleci.com/docs/building-docker-images/#docker-version).
- previous version should work until 9/30, but it's not found today, so...
=> fix: update remote docker version based on circleCI docs

src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
adding `source` to reschedule mutation when moving item to bottom.
=> fix: adding source to mutation when moving item to bottom

src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.tsx, src/curated-corpus/components/ScheduleItemFormConnector/ScheduleItemFormConnector.tsx, src/curated-corpus/components/ScheduleItemModal/ScheduleItemModal.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
As currently implemented, the “Add item” button on the Schedule page is a solitary button on top of the page, and the scheduling date it fills in by default is tomorrow in the curator’s time zone. This was actually not the intention of the new UX wireframes - there should be a button next to each scheduled date. 
Functionality changes:
- There is an “Add an item” for manual addition of stories alongside each date displayed on the Schedule page
- When going through the manual addition, the date automatically filled in should be that parent date rather than tomorrow.
- I have slightly de-emphasised the header for each date and lined up the header/accordion element with the button. Note that the accordion is on the way out - it will be replaced by the new sorting and filtering in the near …
=> feat(scheduling): [MC-784] 'Add item' button should appear next to each date on Schedule page

src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.tsx, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Making sure the removal modal is triggered for `slate_scheduler_v2` prospects. 
https://github.com/Pocket/curation-admin-tools/assets/16909783/c828a254-6fc2-4d7f-bd54-b86c0e857cf7
Tickets:
- [https://mozilla-hub.atlassian.net/browse/MC-772](https://mozilla-hub.atlassian.net/browse/MC-772)
=> feat: Adding removal modal for prospects already in corpus

src/_shared/components/CardActionButtonRow/CardActionButtonRow.test.tsx, src/_shared/components/CardActionButtonRow/CardActionButtonRow.tsx, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx, src/curated-corpus/components/SuggestedScheduleItemListCard/SuggestedScheduleItemListCard.test.tsx, src/curated-corpus/components/SuggestedScheduleItemListCard/SuggestedScheduleItemListCard.tsx, src/curated-corpus/components/actions/RejectAndUnscheduleItemAction/RejectAndUnscheduleItemAction.test.tsx, src/curated-corpus/components/actions/RejectAndUnscheduleItemAction/RejectAndUnscheduleItemAction.tsx, src/curated-corpus/components/index.ts, src/curated-corpus/helpers/scheduledItem.test.ts, src/curated-corpus/helpers/scheduledItem.ts, src/curated-corpus/integration-test-mocks/deleteScheduledCorpusItem.ts, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
When curators press the trash icon on items on the Schedule page, the app now allows them to reject these items and unschedule them in one go as long as that's the only scheduled entry.
If more than one scheduled entry is linked to the same corpus item that the curator is trying to reject, an error message appears instead.
Note: tests test the happy path only in line with existing tests.
Here I'm trying to reject an item but it's scheduled for another date. Once I remove the second scheduling entry, I can reject the item. 
https://github.com/Pocket/curation-admin-tools/assets/22447785/6bb64a2e-a761-49f5-b83c-75092c03845c
https://mozilla-hub.atlassian.net/browse/MC-564
=> feat(scheduling): [MC-564] Launch Reject modal from new Schedule view

src/api/generatedTypes.ts, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.tsx, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
The `source` on a scheduled item was set to `Manual` upon an edit action. This was setting some of the `ML` source items to `Manual` source items. This PR fixes this.
Tickets:
- [https://mozilla-hub.atlassian.net/browse/MC-840](https://mozilla-hub.atlassian.net/browse/MC-840)
=> fix bug: source on scheduled item should not change upon edit action

src/api/fragments/curatedItemData.ts, src/api/fragments/urlMetadata.ts, src/api/generatedTypes.ts, src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.tsx, src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.validation.tsx, src/curated-corpus/components/SuggestedScheduleItemListCard/SuggestedScheduleItemListCard.tsx, src/curated-corpus/components/actions/EditCorpusItemAction/EditCorpusItemAction.tsx, src/curated-corpus/helpers/approvedItem.ts, src/curated-corpus/helpers/prospects.test.ts, src/curated-corpus/helpers/prospects.ts, src/curated-corpus/integration-test-mocks/getScheduledItems.ts, src/curated-corpus/integration-test-mocks/updateApprovedItem.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
- Added the `datePublished` field throughout to be able to add this data when manually adding prospects or curated items. This is a hidden field and the data is supplied by the Pocket Graph for collections and syndicated items and by the Parser for all other stories if available.
- Added the publication date to the new look scheduled item card.
- Updated tests, query and mutation mocks, generated types.
- The publication date is a hidden field for the time being - if the curators need to adjust or view it when adding a curated item manually, we can find a spot for it on the Approved Item form. I didn't want to add any more scope creep to a ticket that started out as a seemingly very small task.
I'm adding an item manually on the Schedule page in the walkthrough; adding an item manually …
=> feat(scheduling): [MC-781] Add publication date to cards in Schedule View

src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.tsx, src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.validation.tsx
This is a follow-up fix to https://github.com/Pocket/curation-admin-tools/pull/1180 which broke editing metadata for existing curated items that don't have a publication date.
=> fix(corpus): Adjust validation for 'datePublished' field to allow for null values

src/api/generatedTypes.ts, src/api/mutations/createScheduledCorpusItem.ts, src/api/mutations/rescheduledScheduledItem.ts, src/curated-corpus/components/actions/EditCorpusItemAction/EditCorpusItemAction.tsx, src/curated-corpus/components/actions/RejectAndUnscheduleItemAction/RejectAndUnscheduleItemAction.test.tsx, src/curated-corpus/components/actions/RejectAndUnscheduleItemAction/RejectAndUnscheduleItemAction.tsx, src/curated-corpus/components/actions/RejectCorpusItemAction/RejectCorpusItemAction.test.tsx, src/curated-corpus/components/actions/RejectCorpusItemAction/RejectCorpusItemAction.tsx, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.test.tsx, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.tsx, src/curated-corpus/integration-test-mocks/createScheduledCorpusItem.ts, src/curated-corpus/integration-test-mocks/deleteScheduledCorpusItem.ts, src/curated-corpus/integration-test-mocks/rejectApprovedItem.ts, src/curated-corpus/pages/CorpusItemPage/CorpusItemPage.tsx, src/curated-corpus/pages/CorpusPage/CorpusPage.tsx, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
send actionScreen value to relevant mutations.
- https://mozilla-hub.atlassian.net/browse/MC-748
=> feat: send actionScreen value to relevant mutations

docker-compose.yml, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.test.tsx, src/curated-corpus/integration-test-mocks/createScheduledCorpusItem.ts, src/curated-corpus/integration-test-mocks/getScheduledSurfacesForUser.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Modify the workflow introduced in https://github.com/Pocket/curation-admin-tools/pull/1183 so that our syndication coordinator does not need to provide reasons when manually adding syndicated articles to the corpus.
https://github.com/Pocket/curation-admin-tools/assets/22447785/ce295b8a-eb4c-4b04-859e-22f924880e20
https://mozilla-hub.atlassian.net/browse/MC-922
=> fix(scheduling): [MC-922] Do not require manual scheduling reasons for syndicated items

src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Unset the last manually added corpus item so that when curators reorder or reschedule other items on the page, the ScheduleItemModal component specific to manually added items is not triggered instead.
Before - with the GraphQL calls in the DevTools panel to demonstrate it was calling the wrong mutation; and after with the right mutation going through on the "Reschedule" action.
Before:
https://github.com/Pocket/curation-admin-tools/assets/22447785/379168f1-cd4e-4fe5-b21e-6d2f310b6794
After:
https://github.com/Pocket/curation-admin-tools/assets/22447785/6ba61e3e-caa8-42cd-941c-c7ea89050ed1
Ref: https://mozilla-hub.atlassian.net/browse/MC-754
=> fix(scheduling): [MC-754] Items are being scheduled for multiple days

src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Fix the bug - rescheduling modal should be showing the correct item and not the latest (manual) item added to the schedule. 
(invalid - was thinking of reordering items rather than rescheduling them) ~~Fix the bug! I have traced this bug to April 2022: https://github.com/Pocket/curation-admin-tools/commit/92d14a6e15e8ef2b9c86c98f9ca126f3c038098e#r141000157 - which means it has been there ever since this feature was introduced, it may not have been used often enough to be detected up until recently.~~
Adding a manual item, then rescheduling a different item - all works as intended now.
https://github.com/Pocket/curation-admin-tools/assets/22447785/bc87346f-737e-488c-98ba-eb641e8f4c98
https://mozilla-hub.atlassian.net/browse/MC-962
=> fix(scheduling): [MC-962] Reschedule button moves the last article posted

src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.test.tsx, src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.tsx, src/curated-corpus/components/ScheduleItemFormConnector/ScheduleItemFormConnector.tsx, src/curated-corpus/components/ScheduleItemModal/ScheduleItemModal.tsx, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Now that the Topic & Publisher summary is hidden by default in an Accordion component to make space for the manual  schedule reasons, let's expand it for syndicated articles to simplify curators' workflow. 
https://github.com/Pocket/curation-admin-tools/assets/22447785/99e378d9-bf4e-4b0c-a462-70bd4da91d2e
https://mozilla-hub.atlassian.net/browse/MC-923
=> feat(scheduling): [MC-923] Expand Topic & Publisher summary for manually scheduled syndicated articles

.github/CODEOWNERS
Update code owners to Content engineers - my previous PR pinged someone on the Pocket team for a review.
This team appears to be up-to-date: https://github.com/orgs/Pocket/teams/content
=> chore(github): Update code owners to Content engineers

src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.test.tsx, src/curated-corpus/components/actions/EditCorpusItemAction/EditCorpusItemAction.test.tsx, src/curated-corpus/integration-test-mocks/updateApprovedItem.ts
Improve test coverage so the incident that is referenced in the JIRA ticket can't happen ever again.
- Updated EditCorpusItemAction tests to add test coverage around not providing a value for `datePublished`. Form-level tests are fine as they are but the edit action is the component that was missing the needed test coverage.
Reference: https://mozilla-hub.atlassian.net/browse/MC-991
=> chore(tests): [MC-991] Improve test coverage for AprovedItemForm

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
When clicking “Schedule” or “Recommend/Add to Corpus” via any New Tab de-de Prospect source, curators will not receive the Manual Add Reasons modal.
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1042
=> MC-1042: do not show manual add reasos for DE New Tab when adding to corpus / recommending from prospecting page

src/curated-corpus/components/RemoveItemFromScheduledSurfaceModal/RemoveItemFromScheduledSurfaceModal.test.tsx, src/curated-corpus/components/RemoveItemFromScheduledSurfaceModal/RemoveItemFromScheduledSurfaceModal.tsx
Provide a reason for unscheduling an item on New Tab DE.
- Enabled unscheduling/removal reasons for NEW_TAB_DE_DE
- Updated tests.
https://github.com/Pocket/curation-admin-tools/assets/22447785/d4f57dc9-d558-4616-9f24-c5fb9a12924f
https://mozilla-hub.atlassian.net/browse/MC-859
=> feat(scheduling): [MC-859] Provide a reason for unscheduling an item on New Tab DE

src/_shared/utils/applyQuotesDashesDE.test.ts, src/_shared/utils/applyQuotesDashesDE.ts, src/curated-corpus/helpers/helperFunctions.test.ts
- Dashes should be changed to `en` dashes not `em` dashes. Fixed & updated tests.
- Accommodate »example« use case, should be changed to „example"
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1190
=> MC-1190: fix German quotes / dashes formatting

src/config/index.ts
Move to Mozilla Auth Proxy instead of our older cognito proxy. this should ameliorate the problem we've faced for years when folks are in too many mozilla groups and access breaks (due to the group size breaking the auth payload size restrictions).
- https://getpocket.atlassian.net/browse/BACK-1505
the client id value in your local `.env` file will need to be updated! ask in slack (or check AWS cognito) for the new value!
=> fix(mozilla): moving to mozilla auth proxy

src/_shared/components/CorpusItemCardImage/CorpusItemCardImage.test.tsx, src/_shared/components/CorpusItemCardImage/CorpusItemCardImage.tsx, src/api/generatedTypes.ts, src/curated-corpus/components/ScheduleDayData/ScheduleDayData.tsx, src/curated-corpus/components/ScheduleDayFilterRow/ScheduleDayFilterRow.tsx, src/curated-corpus/components/ScheduleDayHeading/ScheduleDayHeading.tsx
- Add a new filter ("ML-Syndicated") to the "Types" filter dropdown. This is where ML-scheduled syndicated stories are now grouped to, separate to other ML stories. 
- Tweak card labels to show "ML-Syndicated" with a magic wand icon where ML-scheduled stories are syndicated, and keep the "ML" tag for other ML-scheduled items.
- Add/update tests for new functionality.
Note: demo is up on Dev.
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1273
- https://mozilla-hub.atlassian.net/browse/MC-1274
=> feat(scheduling): MC-1273, MC-1274 Add 'ML-Scheduled' to filters and scheduled item card

src/api/generatedTypes.ts, src/curated-corpus/helpers/prospects.test.ts
update generated types to remove syndicated prospect sources
- syndicated prospect sources have been deprecated by ML
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1357
=> chore: update generated types to remove syndicated prospect sources

src/curated-corpus/components/ScheduleDayData/ScheduleDayData.tsx
It appears the initial PR that added filters to the Schedule page did not filter out ML-Syndicated items out of the ML filter 
correctly. The dropdown numbers shown were correct, however the actual filters were not applied correctly. 
I _think_ this is because we didn't have enough data to test on Dev with, and that is why the bug must have slipped through. With the data we had at the time, everything looked to be working as expected. 
https://mozilla-hub.atlassian.net/browse/MC-1273?focusedCommentId=919426
=> fix(filters): [MC-1273] Make sure ML-filtered items don't include Syndicated items

src/api/generatedTypes.ts, src/curated-corpus/integration-test-mocks/getScheduledSurfacesForUser.ts
What changed? What is the business/product goal?
The Editors would like to have easy access to stories suggested by external publishers. 
They are currently being submitted via airtable.
We already have ingestion in our German auto-scheduler, so we are leveraging that to output a new prospect feed in this PR
https://github.com/MozillaSocial/ml-services/pull/430
New type is added in https://github.com/Pocket/content-monorepo/pull/213
References to deprecated Syndication prospect feed are removed as well.
Named the prospect source ExternalEditorial so users know these are external links and thus unvetted. 
Only URLs from previously published domains are sent to this feed. We might consider additional security checks in the future.
JIRA ticket:
[
- Link to JIRA …
=> Mc 1404 create prospecting source for publisher air table suggestions

src/api/generatedTypes.ts, src/curated-corpus/components/RejectItemForm/RejectItemForm.test.tsx, src/curated-corpus/components/RejectItemForm/RejectItemForm.tsx, src/curated-corpus/components/RejectItemForm/RejectItemForm.validation.tsx
Add the new rejection reason (`Publisher Request`) to Curation Tools frontend so that curators can start using it where necessary. 
Testing: I have verified it works after deploying the backend change to Dev.
There are two more reasons available on the backend that we're NOT using on the frontend. These are `COMMERCIAL` and `PUBLISHER_QUALITY`. Should we add them, too?
https://mozilla-hub.atlassian.net/browse/MC-1446
=> feat(corpus): [MC-1446] Add new 'Publisher Request' rejection reason

src/curated-corpus/components/ScheduleDayData/ScheduleDayData.tsx, src/curated-corpus/components/ScheduleDayFilterRow/ScheduleDayFilterRow.tsx
Add a filter for the `isTimeSensitive` property of corpus items so that curators can narrow down the list of scheduled items to just the time-sensitive ones. Note: no updates to tests as we don't test for the presence of each and every dropdown option in the filters; otherwise filter-related test coverage is good.
Note: deployed to Dev for a more easily accessible demo. Screenshot below:
https://mozilla-hub.atlassian.net/browse/MC-1502
=> feat(corpus): [MC-1502] Filter schedule view by 'time-sensitive' on all surfaces

src/api/generatedTypes.ts, src/curated-corpus/helpers/definitions.ts, src/curated-corpus/helpers/topics.test.ts
See notes in https://mozilla-hub.atlassian.net/browse/MC-1248 for when this feature is going to production.
Allow the curators to categorise stories as belonging to the brand new "Home" category. 
- Note: with regenerating types, a handful of unrelated schema changes have sneaked through. I think that is fine - we'll use them in the near future anyway. It's also possible that these schema changes will be merged to `main` earlier than this PR is deployed, in which case the changes will be removed from this PR.
https://mozilla-hub.atlassian.net/browse/MC-1251
=> feat(topics): Add new 'Home' topic as an option in the tool

src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.test.tsx, src/curated-corpus/components/ScheduleItemForm/ScheduleItemForm.validation.tsx
Fix a bug described in the title of this PR.
- Updated validation rules for `scheduledDate` to evaluate today's timestamp that is the equivalent of the start of the day, and not any random time that occasionally prevented curators from schedulind.
- Updated validation messages to provide feedback to users when form validation fails.
- Removed an outdated prospect source from tests.
https://mozilla-hub.atlassian.net/browse/MC-1554
=> fix(scheduling): [MC-1554] Fix same day scheduling from Schedule view

src/curated-corpus/helpers/definitions.ts, src/curated-corpus/helpers/topics.test.ts
Upon adding, editing an item, ensure "Coronavirus" is not in the Topics list. For existing items with "Coronavirus" topic, the topic will be displayed as "N/A"
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1556
=> MC-1556: Ensure ‘Coronavirus’ is not available as a Topic when adding an Item

src/_shared/utils/applyApTitleCase.test.ts, src/_shared/utils/applyApTitleCase.ts
Fix the capitalization rules for english titles:
* Capitalize the word "so" (remove as a stop word)
* Capitalize the first word (regardless if it is a stop word) after a quote: `'the day'` -> `'The Day'`
* Ensure there is a difference between a quote and apostrophe: `'the day' day'S` -> `'The Day' Day's`
* Capitalize word after a colon (:): '`the day' day's: day` -> `'The Day' Day's: Day`
Final result: `Amorim aims to 'prove something' at Manchester United after agreeing deal: read the day's 'news'` -> `Amorim Aims to ‘Prove Something’ at Manchester United After Agreeing Deal: Read the Day’s ‘News’`
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1583
=> MC-1583:"Fix Title” for English titles not capitalizing first word after single quote or colon

src/_shared/utils/applyApTitleCase.test.ts, src/_shared/utils/applyApTitleCase.ts
Fix the apostrophe formatting for English titles. Currently, words with an apostrophe + 1 letter following the apostrophe have been formatted correctly:`bat'S` -> `bat's`.
Words with 2+ letters following an apostrophe were not formatted correctly: `you'll` -> `You'Ll`.
Desired output: `you'll` -> `You'll`
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1594
=> MC-1594: Fix English title apostrophe formatting

src/api/generatedTypes.ts, src/api/mutations/createScheduledCorpusItem.ts, src/api/mutations/rescheduledScheduledItem.ts, src/curated-corpus/components/RemoveItemFromScheduledSurfaceModal/RemoveItemFromScheduledSurfaceModal.test.tsx, src/curated-corpus/components/ScheduleDayData/ScheduleDayData.tsx, src/curated-corpus/components/ScheduleDayFilterRow/ScheduleDayFilterRow.tsx, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx, src/curated-corpus/components/actions/ScheduleCorpusItemAction/ScheduleCorpusItemAction.tsx, src/curated-corpus/helpers/scheduledItem.ts, src/curated-corpus/integration-test-mocks/createScheduledCorpusItem.ts, src/curated-corpus/integration-test-mocks/getScheduledItems.ts, src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx, src/curated-corpus/pages/SchedulePage/SchedulePage.tsx
Updating generated types, replacing `ScheduledItemSource` enum with `ActivitySource` enum.
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1646
=> MC-1646: updating generated types

src/_shared/components/Header/Header.tsx, src/api/fragments/SectionData.ts, src/api/fragments/SectionItemData.ts, src/api/generatedTypes.ts, src/api/queries/getSectionsWithSectionItems.ts, src/curated-corpus/pages/CuratedCorpusLandingPage/CuratedCorpusLandingPage.tsx, src/curated-corpus/pages/SectionsPage/SectionsPage.tsx, src/curated-corpus/pages/index.ts
Adding the initial basic read-only page to manage Sections.
Added the menu / header link to the new Sections page.
- Calling the admin `getSectionsWithSectionItems` query & displaying Section titles (per scheduled surface).
Demo:
https://github.com/user-attachments/assets/26367586-5ae4-4d20-8820-0c4f798f19b5
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1655
=> MC-1655: Adding the initial read-only page to manage Sections

src/_shared/components/CardActionButtonRow/CardActionButtonRow.test.tsx, src/_shared/components/CardActionButtonRow/CardActionButtonRow.tsx, src/api/generatedTypes.ts, src/api/mutations/removeSectionItem.ts, src/curated-corpus/components/SectionDetails/SectionDetails.test.tsx, src/curated-corpus/components/SectionDetails/SectionDetails.tsx, src/curated-corpus/components/SectionItemCardWrapper/SectionItemCardWrapper.tsx, src/curated-corpus/pages/SectionsPage/SectionsPage.tsx
Wiring up actions for editing corpus metadata on a `SectionItem` & removing a `SectionItem`.
* Added new `onRemove` callback to `CardActionButtonRow` to differentiate between the `onReject` callback. Using the `ClearIcon` (X) for the remove button.
* Updated `SectionDetails` component tests.
https://github.com/user-attachments/assets/3f86cdb9-9c81-4b19-97a3-541f783ba124
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1656
=> MC-1656: adding edit & remove section item actions

src/_shared/components/CardActionButtonRow/CardActionButtonRow.test.tsx, src/_shared/components/CardActionButtonRow/CardActionButtonRow.tsx, src/_shared/components/index.ts, src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx, src/curated-corpus/components/SectionItemCardWrapper/SectionItemCardWrapper.tsx, src/curated-corpus/components/StoryItemListCard/StoryItemListCard.test.tsx
Abstract the `CardActionButtonRow` component to be more generic & not need to know about all card button actions across different component.
* Added new `CardAction` type to take in the action name, MUI icon & `onClick` callback.
* Adjusted `CardActionButtonRowProps` to take an array of (optional) right-aligned `CardAction` & (optional) left-aligned `CardAction`.
Components can now specify right and/or left card action buttons like this:
```
// card action buttons to be rendered & aligned on bottom left
const cardActionButtonsLeft: CardAction[] = [
{ actionName: 'Edit', icon: <EditOutlinedIcon />, onClick: () => onEdit() },
];
// card action buttons to be rendered & aligned on bottom right
const cardActionButtonsRight: CardAction[] = [
{ actionName: 'Remove', icon: <ClearIcon />, onClick: …
```
=> (chore)MC-1676: CardActionButtonRow component refactor

src/curated-corpus/components/SectionDetails/SectionDetails.test.tsx, src/curated-corpus/components/SectionDetails/SectionDetails.tsx, src/curated-corpus/components/SectionItemCardWrapper/SectionItemCardWrapper.tsx, src/curated-corpus/pages/SectionsPage/SectionsPage.tsx
Adding rejection action for section items.
- Adding reject button (trash icon) to section items
- Displaying rejection reasons modal (same reasons for rejecting an approved corpus item)
- Calling `rejectApprovedCorpusItem` mutation
https://github.com/user-attachments/assets/8d8d7b30-06f8-419e-b977-16801b9a345b
Tickets:
- https://mozilla-hub.atlassian.net/browse/HNT-504
=> HNT-504: adding rejection reasons modal for section items

src/api/fragments/SectionData.ts, src/api/generatedTypes.ts, src/curated-corpus/components/SectionDetails/SectionDetails.test.tsx, src/curated-corpus/components/SectionDetails/SectionDetails.tsx, src/curated-corpus/helpers/helperFunctions.test.ts, src/curated-corpus/helpers/helperFunctions.ts
Display the full IAB label for an ML Section. 
Curators approved the IAB label placement ([slack thread](https://mozilla.slack.com/archives/C05EVRU1U1X/p1746553916031829)).
Tickets:
- https://mozilla-hub.atlassian.net/browse/HNT-582
=> HNT-582: render full IAB label for a Section

src/curated-corpus/components/SectionDetails/SectionDetails.test.tsx, src/curated-corpus/components/SectionDetails/SectionDetails.tsx
Display section description when provided
https://github.com/user-attachments/assets/63624fa9-91ac-44f5-8334-7c9ddd3a1ed0
Tickets:
- https://mozilla-hub.atlassian.net/browse/HNT-970
=> HNT-970: Optionally display Section description
