src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.test.tsx
src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.tsx

remove the curator from the approved item card.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1332

refactor(item card): remove curator/createdBy from display

---

src/curated-corpus/components/ApprovedItemSearchForm/ApprovedItemSearchForm.test.tsx
src/curated-corpus/components/ApprovedItemSearchForm/ApprovedItemSearchForm.tsx
src/curated-corpus/components/RejectedItemSearchForm/RejectedItemSearchForm.tsx
src/curated-corpus/components/RejectedItemSearchForm/RejectedtemSearchForm.test.tsx

1. Show all default results when resetting search form filters
2. Bolster tests
https://user-images.githubusercontent.com/16694733/156809316-98ab8524-9c0d-45ae-adaf-e3c80c7cfeb4.mov

feat(reset filters): show all results after resetting filters and update tests

---

src/curated-corpus/helpers/helperFunctions.ts

Update error message when image  image download fails due to CORS/other issues
Tickets:
- [BACK-1349]
[BACK-1349]: https://getpocket.atlassian.net/browse/BACK-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(upload error message): [BACK-1349] Update error message for failed image download

---

src/api/fragments/scheduledItemData.ts
src/api/generatedTypes.ts
src/api/mutations/rescheduledScheduledItem.ts
src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.test.tsx
src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx
src/curated-corpus/pages/SchedulePage/SchedulePage.tsx

Add the `Reschedule` button to the scheduled item on the scheduling page
Tickets:
- [BACK-1337]
[BACK-1337]: https://getpocket.atlassian.net/browse/BACK-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/16694733/156849356-e9089cd9-2858-43ff-8252-d78679c4bc46.mov

feat(reschedule button): [BACK-1337] add reschedule button

---

src/api/fragments/scheduledItemData.ts
src/api/generatedTypes.ts
src/api/queries/getScheduledItems.ts
src/curated-corpus/components/AddProspectFormConnector/AddProspectFormConnector.tsx
src/curated-corpus/components/ApprovedItemForm/ApprovedItemForm.tsx
src/curated-corpus/components/ApprovedItemModal/ApprovedItemModal.tsx
src/curated-corpus/components/ImageUpload/ImageUpload.tsx
src/curated-corpus/helpers/definitions.ts
src/curated-corpus/helpers/helperFunctions.test.ts
src/curated-corpus/helpers/helperFunctions.ts
src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx

Update `language` field mapping for prospect item
**aside:** add scheduledSurfaceGuid field to getScheduledItems query
Tickets:
- N/A

chore(language): Update language field mapping for prospect item

---

src/_shared/components/Header/Header.styles.tsx
src/config/index.ts

To make the **_Dev_** branch version visually distinctive
Tickets:
- [BACK-1370]
[BACK-1370]: https://getpocket.atlassian.net/browse/BACK-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(styles): [BACK-1370] make dev curation tools visually distinctive

---

.aws/package-lock.json
.aws/package.json
.aws/src/pocketAlbApplication.ts

We need to send notifications for failed deploys only 
JIRA ticket:
* [INFRA-421]
[INFRA-421]: https://getpocket.atlassian.net/browse/INFRA-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(notifications): [INFRA-421] Update code deploy notifications to fire on failed deploys only

---

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx

fix the input varialbe for the schedule and reject flow for the `updateProspectAsCurated` mutation

fix(input variable): update prospectId to id for the input variable for updateProspectAsCurated mutation

---

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx

Send prospectId when rejecting a prospect.

fix(prospect ID): Rejecting prospects

---

src/api/generatedTypes.ts

chore(shared data): add prospect type

---

src/_shared/utils/flattenAuthors.ts
src/api/generatedTypes.ts
src/curated-corpus/components/ApprovedItemCardWrapper/ApprovedItemCardWrapper.test.tsx
src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.test.tsx
src/curated-corpus/components/ApprovedItemListCard/ApprovedItemListCard.tsx
src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.test.tsx

update generated types to guarantee authors data.
(do we need any actual code changes for this? maybe not?)
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1497

chore(generatedTypes): guarantee authors data

---

src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx

Fix data flickering on Prospecting page on initial render. This also fixes the error message being shown due to a request being made with an empty (`""`) guid.
Tickets:
- [BACK-1481]
[BACK-1481]: https://getpocket.atlassian.net/browse/BACK-1481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(initial render): [BACK-1481] Data flickers and disappears on prospecting page

---

src/curated-corpus/components/AddProspectModal/AddProspectModal.test.tsx

Add a unit test for `AddProspectModal` component
Tickets:
- [BACK-1526]
[BACK-1526]: https://getpocket.atlassian.net/browse/BACK-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tests): [BACK-1526] Add unit test for AddProspectModal component

---

src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.test.tsx

Improve test coverage to near perfect levels :).
- Added unit tests for button actions.
https://getpocket.atlassian.net/browse/BACK-1533

chore(tests): [BACK-1533] Improve unit tests for ScheduledItemCardWrapper component

---

src/curated-corpus/components/ProspectListCard/ProspectListCard.test.tsx

Still on the quest to improve test coverage for this repository.
- Added unit tests for action buttons.
https://getpocket.atlassian.net/browse/BACK-1528

chore(tests): [BACK-1528] Improve tests for ProspectListCard component

---

src/curated-corpus/components/RefreshProspectsModal/RefreshProspectsModal.test.tsx

Increase test coverage!
https://getpocket.atlassian.net/browse/BACK-1529

chore(tests): [BACK-1529] Add unit tests for RefreshProspectsModal component

---

src/curated-corpus/components/ApprovedItemModal/ApprovedItemModal.test.tsx

Add missing unit tests for `ApprovedItemModal` component
Tickets:
- [BACK-1527]
[BACK-1527]: https://getpocket.atlassian.net/browse/BACK-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tests): [BACK-1527] add unit tests for ApprovedItemModal component

---

src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.test.tsx
src/curated-corpus/components/RejectItemModal/RejectItemModal.test.tsx

Add unit tests for `RejectItemModal` component
Tickets:
- [BACK-1531]
[BACK-1531]: https://getpocket.atlassian.net/browse/BACK-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tests): [BACK-1531] Add unit tests for RejectedItemModal component

---

src/curated-corpus/components/ApprovedItemCurationHistory/ApprovedItemCurationHistory.tsx
src/curated-corpus/components/ApprovedItemInfo/ApprovedItemInfo.tsx
src/curated-corpus/pages/CorpusItemPage/CorpusItemPage.tsx

Implement review feedback from https://github.com/Pocket/curation-admin-tools/pull/910

chore(cleanup): [BACK-1490] Add comments and clean up code

---

src/_shared/components/FloatingActionButton/FloatingActionButton.tsx
src/curated-corpus/pages/SchedulePage/SchedulePage.tsx

Fix some console warnings we were getting on the dev environment. Helped us remove some redundant and dead code.
🍐 with @nina-py

chore(console warnings): fix console warnings

---

src/curated-corpus/components/AddProspectFormConnector/AddProspectFormConnector.tsx
src/curated-corpus/helpers/helperFunctions.test.ts
src/curated-corpus/helpers/helperFunctions.ts
src/curated-corpus/helpers/prospects.test.ts
src/curated-corpus/helpers/prospects.ts

Update and add some unit tests for some of the helper functions.
Tickets:
- [BACK-1557]
[BACK-1557]: https://getpocket.atlassian.net/browse/BACK-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACK-1557] Add unit tests for helper functions

---

src/curated-corpus/components/AddProspectModal/AddProspectModal.test.tsx
src/curated-corpus/components/ApprovedItemCurationHistory/ApprovedItemCurationHistory.test.tsx
src/curated-corpus/components/ScheduleItemFormConnector/ScheduleItemFormConnector.test.tsx

- We have this one test that is very flaky. Usually we've been getting past it by re-running the build at different times but it has been a hassle. Making it consistent across time zones now.
- fix other lint errors. 😕 These were caught by husky and I'm surprised weren't caught by the CI lint check??

refactor: fix flaky test failing due to local dev machine and CI server system timezone differences

---

src/api/generatedTypes.ts
src/curated-corpus/helpers/definitions.ts

Update `generatedTypes` to inclued newly added `FR, ES, IT` languages.
Tickets:
- INFRA-1131
https://user-images.githubusercontent.com/16694733/230213066-1fe5acc0-67ea-4523-b221-e02b8cfbbd31.mov

feat(CorpusLanguage): [INFRA-1131] Add FR,ES,IT CorpusLanguage enum values

---

src/api/fragments/BasicParserItemData.ts
src/api/fragments/prospectWithCorpusItems.ts
src/api/generatedTypes.ts
src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.test.tsx
src/curated-corpus/components/ExistingProspectCard/ExistingProspectCard.tsx
src/curated-corpus/components/ProspectListCard/ProspectListCard.tsx
src/curated-corpus/components/ProspectPublisherFilter/ProspectPublisherFilter.test.tsx
src/curated-corpus/components/ProspectPublisherFilter/ProspectPublisherFilter.tsx
src/curated-corpus/pages/ProspectingPage/ProspectingPage.tsx

Rebased from Rolf's `rolf-TML-98-prospect-item` branch.
This pr adds the published date and the sort by published date button in the Prospecting tool
Tickets:
- Rolf's work to add item to frontend - https://getpocket.atlassian.net/browse/TML-98
- Sort by published date - https://getpocket.atlassian.net/browse/TML-108

Published date + sort by date

---

src/curated-corpus/components/ScheduledItemCardWrapper/ScheduledItemCardWrapper.tsx
src/curated-corpus/pages/SchedulePage/SchedulePage.tsx

Per editors' request, remove schedule context from schedule page (https://mozilla.slack.com/archives/C05FLVAF4SK/p1689719662331439?thread_ts=1689620560.445929&cid=C05FLVAF4SK)
Tickets:
- [Jira](https://getpocket.atlassian.net/browse/TML-137)

Remove schedule context from schedule page

---

README.md
src/collections/components/CollectionForm/CollectionForm.test.tsx
src/collections/components/CollectionForm/CollectionForm.tsx

Add fix quotes buttons to excerpts & intro part of collection
Fix tests
Tickets:
- [Jira](https://getpocket.atlassian.net/browse/TML-127)

Fix quotes to collection excerpt & intro

---

.aws/src/pocketAlbApplication.ts
buildspec.yml

Update var PAGERDUTY_TOKEN and escalations in main.ts

---

src/api/generatedTypes.ts
src/curated-corpus/integration-test-mocks/getScheduledSurfacesForUser.ts

Add new prospect type `SLATE_SCHEDULER`.
JIRA Ticket:
- https://mozilla-hub.atlassian.net/browse/MC-435

feat(prospectType): [MC-403] Add SLATE_SCHEDULER

---

src/curated-corpus/pages/SchedulePage/SchedulePage.tsx

fix: correct variable name in reschedule mutation

---

src/api/generatedTypes.ts
src/api/queries/getScheduledItems.ts

- This removes a TypeScript error from the SchedulePage component.
Follow-up fix to https://mozilla-hub.atlassian.net/browse/MC-763.

fix(scheduling): Add source field to query fragment; update generated types

---

src/api/generatedTypes.ts

should merge directly after https://github.com/Pocket/content-monorepo/pull/120 merges.
update types to remove sunset prospect sources
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-876

chore: update types to remove sunset prospect sources

---

.aws/src/config/index.ts
.aws/src/main.ts
.aws/src/pocketAlbApplication.ts

fix(tags): adding in cost center tags

---

.circleci/config.yml

Upgrading circleCI aws-ecr to V9
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1553

MC-1553: upgrade circleci aws-ecr to V9

---

src/api/generatedTypes.ts

update generated types
- removes deprecated prospect sources
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1542

chore: update generated types

---

src/api/generatedTypes.ts

update generated types to get new QA prospect types in the tool (not yet coming in from ML).
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1612

chore: update generated types to add QA prospect types

---

src/api/generatedTypes.ts

update generated types to get latest QA prospect types in the tool.

chore: update generated types (prospect types)

---

src/api/fragments/SectionData.ts
src/api/generatedTypes.ts
src/api/mutations/disableEnableSection.ts
src/curated-corpus/components/SectionDetails/SectionDetails.test.tsx
src/curated-corpus/components/SectionDetails/SectionDetails.tsx

Adding a "Disable/Enable" toggle switch for Sections.
Demo:
https://github.com/user-attachments/assets/97e1a81d-d851-4209-8347-8c485fa27635
Tickets:
- https://mozilla-hub.atlassian.net/browse/MC-1680

MC-1680: adding a disable/enable switch for Sections

---

src/_shared/utils/applyApTitleCase.test.ts
src/_shared/utils/applyApTitleCase.ts
src/curated-corpus/components/ProspectFilters/ProspectFilters.test.tsx

Mirror fix in https://github.com/Pocket/content-monorepo/pull/282

[MC-1682] fix: capitalization after curly apostrophe
